const ar = {
  app_title: "منصة الإعلانات والروابط",

  nav_home: "الرئيسية",
  nav_wallet: "المحفظة",
  nav_ads: "الحملات",
  nav_referral: "الإحالة",
  nav_settings: "الإعدادات",

  deposit_guide_title: "دليل الشحن ورمز العملية TxID",
  guide_step1_title: "اختر الشبكة:",
  guide_step1_desc: "اختر (USDT TRC20 أو BEP20) لعرض عنوان الإيداع الخاص بك، ثم انقر على نسخ.",
  guide_step1_copy: "نسخ",
  guide_step2_title: "تحويل الأموال:",
  guide_step2_desc: "افتح محفظتك (Binance, Trust Wallet, OKX) وأرسل المبلغ المطلوب للعنوان المنسوخ بدقة.",
  guide_step3_title: "نسخ رمز المعاملة (TxID):",
  guide_step3_desc: "بعد اكتمال التحويل، انسخ رقم العملية (TxID / Transaction Hash).",
  txid_hash_label: "TxHash / TxID",
  txid_example_label: "مثال على صيغة TxID:",
  guide_step4_title: "تقديم الطلب:",
  guide_step4_desc: "أدخل قيمة المبلغ ورقم التحويل في الخانات المخصصة واضغط تأكيد الإيداع.",
  guide_step4_btn: "إرسال طلب الإيداع",
  btn_close: "إغلاق",

  bridge_title: "جارٍ تحويلك إلى الرابط...",
  bridge_desc: "يرجى الانتظار لبضع ثوانٍ ثم الضغط على الزر أدناه لمتابعة الانتقال.",
  ad_loading: "إعلان مدعوم",
  timer_text: "سيفعل الزر خلال:",
  seconds: "ثوانٍ",
  go_button: "متابعة إلى الرابط",
  rights_reserved: "جميع الحقوق محفوظة لـ",
  powered_by: "بواسطة",
  official_channel: "📢 القناة الرسمية",

  premium_badge: "مميز ⭐",

  about_title: "ℹ️ نبذة وشروط الاستخدام",
  about_desc: "هذا البوت مخصص لاختصار الروابط بأمان وإدارة الحملات الإعلانية بكفاءة عالية.",
  create_link_title: "اختصار رابط جديد",
  ph_link_title: "عنوان الرابط (اختياري)",
  ph_link_url: "الرابط الأصلي (https://...)",
  btn_shorten: "اختصار الآن",
  my_links_title: "روابطي المختصرة",

  pending_bal: "الرصيد المعلق",
  avail_bal: "الرصيد المتاح",
  tab_deposit: "إيداع",
  tab_withdraw: "سحب",
  deposit_title: "إيداع رصيد للإعلانات",
  deposit_guide_btn: "تعليمات الإيداع المهمة",
  select_network_label: "اختر شبكة الدفع:",
  select_network_option: "اختر شبكة الدفع",
  net_trc20_option: "USDT (TRC20)",
  net_bep20_option: "USDT (BEP20)",
  addr_trc20_label: "عنوان الإيداع (TRC20):",
  addr_bep20_label: "عنوان الإيداع (BEP20):",
  btn_copy: "نسخ",
  submit_proof_label: "إرسال إثبات الإيداع:",
  ph_deposit_amount: "المبلغ المودع ($)",
  ph_deposit_txhash: "معرف المعاملة TxID / Hash",
  btn_submit_deposit: "تأكيد الإيداع",
  withdraw_request_title: "سحب الأرباح",
  wallet_addr_label: "عنوان محفظتك المعين للسحب:",
  ph_wallet_addr: "لم يتم تعيين محفظة",
  btn_edit: "تعديل",
  btn_save_wallet: "حفظ العنوان الجديد",
  ph_withdraw_amount: "المبلغ المراد سحبه (الحد الأدنى $30)",
  calc_req_label: "المطلوب:",
  calc_fee_label: "العمولة (10%):",
  calc_net_label: "الصافي:",
  btn_submit_withdraw: "إرسال طلب السحب",
  withdraw_history: "سجل السحوبات",

  create_ad_title: "إنشاء حملة إعلانية جديدة",
  ad_rate_desc: "تكلفة الإعلان: $1.50 لكل 1,000 مشاهدة حقيقية (CPM)",
  ph_ad_title: "عنوان الإعلان",
  ph_ad_target_url: "رابط الوجهة (https://...)",
  ph_ad_budget: "ميزانية الحملة ($)",
  btn_launch_ad: "إطلاق الحملة",
  my_ads_title: "حملاتي الإعلانية",

  ref_title: "نظام الإحالة والتسويق",
  ref_desc: "احصل على نسبة من أرباح أصدقائك المنضمين عبر رابطك الخاص مدى الحياة!",
  btn_share_ref: "مشاركة عبر تيليجرام",
  total_ref_earnings: "إجمالي أرباح الإحالة",

  lang_settings_title: "تغيير اللغة / Language",
  faq_title: "الأسئلة الشائعة والدعم",
  faq_q1: "كيف يتم احتساب الأرباح؟",
  faq_a1: "تعتمد الأرباح على إيرادات الإعلانات وتوزع نسبياً حسب الزيارات الحقيقية المعتمدة.",
  faq_q2: "ما هي فترة الرصيد المعلق (يوم واحد)؟",
  faq_a2: "هي فترة أمان لمراجعة مصادر الحركة والتأكد من عدم وجود نقرات وهمية.",
  support_text: "للتواصل والدعم الفني عبر التليجرام:",
  bot_official: "🤖 البوت الرسمي",
  channel_official: "📢 القناة الرسمية",
  support_btn: "🎧 الدعم الفني",

  admin_total_users: "المستخدمين",
  admin_total_pending: "معلقات أرباح",
  admin_distribute_title: "توزيع الإيرادات",
  ph_revenue_amount: "إجمالي الإيرادات ($)",
  btn_distribute_rev: "توزيع الإيرادات على الروابط",
  admin_pending_deposits: "طلبات الإيداع المعلقة:",
  no_pending_deposits: "لا توجد طلبات إيداع معلقة.",
  admin_pending_withdraws: "طلبات السحب المعلقة:",
  no_pending_withdraws: "لا توجد طلبات سحب معلقة.",
  admin_user_mgmt: "لوحة التحكم الإدارية",
  approve_btn: "موافقة",
  reject_btn: "رفض",

  loading: "جاري التحميل...",
  copied: "تم النسخ بنجاح!",
  copy_failed: "فشل النسخ تلقائياً",
  cancel: "إلغاء",
  network_error: "تعذر الاتصال بالشبكة، يرجى التحقق من اتصال الإنترنت لديك.",
  link_success_msg: "تم اختصار الرابط بنجاح!",
  auth_failed: "فشل الاتصال بمركز المصادقة",
  no_withdraw_history: "لا توجد طلبات سحب سابقة.",
  no_links_yet: "لا توجد روابط مُختصرة حالياً.",
  no_ads_yet: "لا توجد حملات إعلانية نشطة حالياً.",
  untitled_link: "رابط بدون عنوان",
  status_active: "نشط",
  status_disabled: "معطل",
  status_pending: "قيد المراجعة",
  status_completed: "مكتمل",
  status_rejected: "مرفوض",
  btn_enable: "تفعيل",
  btn_disable: "تعطيل",
  btn_pause: "إيقاف مؤقت",
  btn_activate: "تفعيل",
  views_label: "الزيارات:",
  valid_label: "المعتمدة:",
  remaining_budget: "الميزانية المتبقية:",
  link_activated: "تم تفعيل الرابط",
  link_disabled: "تم تعطيل الرابط",
  toggle_link_error: "خطأ أثناء تغيير حالة الرابط",
  ad_status_updated: "تم تحديث حالة الحملة الإعلانية",
  toggle_ad_error: "خطأ أثناء تعديل حالة الإعلان",
  fill_ad_details: "يرجى ملء جميع البيانات المطلوب الإعلان عنها",
  ad_success: "تم إنشاء الحملة الإعلانية وإطلاقها بنجاح!",
  ad_unexpected_error: "حدث خطأ غير متوقع أثناء إطلاق الحملة",
  select_network_first: "يرجى تحديد نوع الشبكة أولاً",
  enter_valid_amount: "يرجى إدخال مبلغ الشحن الصحيح",
  enter_valid_txid: "يرجى إدخال رمز العملية TxID الخاص بالمعاملة",
  deposit_success: "تم إرسال طلب الشحن بنجاح!",
  deposit_error: "خطأ أثناء تقديم طلب الشحن",
  submit_deposit_btn_text: "تأكيد وإرسال طلب الشحن",
  share_text: "انضم إليّ في أفضل منصة لاختصار الروابط واكسب الأرباح بسهولة! 🚀",
  enter_original_url: "يرجى إدخال الرابط الأصلي بشكل صحيح",
  unexpected_error: "حدث خطأ غير متوقع",
  enter_wallet_first: "يرجى إدخال عنوان محفظة السحب أولاً",
  min_withdraw_error: "الحد الأدنى للسحب هو 30$",
  withdraw_success: "تم تقديم طلب السحب بنجاح!",
  withdraw_process_error: "خطأ أثناء معالجة الطلب",
  invalid_wallet: "عنوان المحفظة غير صالح",
  wallet_saved: "تم حفظ المحفظة بنجاح",
  settings_save_error: "خطأ أثناء حفظ الإعدادات",
  redirect_error: "خطأ أثناء عملية التوجيه",
  server_error: "فشل الاتصال بالخادم"
};

export default ar;
