const enTranslations = {
  nav_home: "Home",
  nav_wallet: "Wallet",
  nav_ads: "Ads",
  nav_referral: "Referrals",
  nav_settings: "Settings",
  pending_bal: "Pending Balance",
  avail_bal: "Available Balance",
  create_link_title: "Shorten New Link",
  ph_link_title: "Title (Optional)",
  ph_link_url: "Original URL (https://...)",
  btn_shorten: "Shorten Link Now",
  my_links_title: "Your Links",
  withdraw_request_title: "Withdraw Earnings",
  wallet_addr_label: "Withdrawal Wallet (USDT TRC20)",
  btn_edit: "Edit",
  btn_save_wallet: "Save New Address",
  btn_submit_withdraw: "Request Withdrawal",
  withdraw_history: "Withdrawal History",
  create_ad_title: "Create New Ad Campaign",
  ad_rate_desc: "Ad Rate: $1.50 per 1,000 real impressions (CPM)",
  ph_ad_title: "Ad Title",
  ph_ad_target_url: "Target URL (https://...)",
  ph_ad_budget: "Total Budget (Min. $5)",
  btn_launch_ad: "Launch Ad Campaign",
  my_ads_title: "Your Ad Campaigns",
  ref_title: "Referral System (10%)",
  ref_desc: "Invite your friends and instantly earn 10% of their total revenues.",
  btn_share_ref: "Share Link via Telegram",
  total_ref_earnings: "Total Referral Earnings",
  lang_settings_title: "Language / تغيير اللغة",
  faq_title: "FAQ & Support",
  faq_q1: "How are earnings calculated?",
  faq_a1: "Earnings depend on ad revenue and are distributed proportionally based on verified visits.",
  faq_q2: "What is the 1-day pending period?",
  faq_a2: "It is a hold period to review traffic sources and prevent fraud before transferring earnings to available balance within 1 day.",
  support_text: "Contact technical support on Telegram:",
  loading: "Loading...",
  copied: "Copied successfully!",
  bridge_title: "Preparing your link...",
  bridge_desc: "Please wait while we redirect you to your destination",
  ad_loading: "Loading advertisement...",
  timer_text: "Button unlocks in:",
  seconds: "seconds",
  go_button: "Continue to Destination",
  cancel: "Cancel",
  network_error: "Network connection error. Please check your internet connection.",
  about_title: "ℹ️ About & Terms of Use",
  about_desc: "This bot is securely dedicated to shortening links and managing promotional campaigns safely. By using this platform, you agree to comply with our traffic quality guidelines and terms of service.",
  link_success_msg: "Link shortened successfully!"
};
